### ISSUE TITLE
Non inclusion proof?

### ISSUE THREAD

**Issue by McFranko** [thyeem/monotree#4]
It says that you can generate non inclusion proofs, but there doesn't seem to be any method provided for doing that?

**Comment by thyeem** [comment]
Sorry for heavily late reply and thanks for your interest.

As you pointed out, there's no explicit method provided like `check_non_inclusion()`.
However, the `monotree` already has that intrinsic feature. Remember that the `monotree` is a Sparse Merkle Tree :)

Just follow the key path you want to read.
(using the monotree's `get()` method: https://github.com/thyeem/monotree/blob/master/src/tree.rs#L105)

If there's nothing (`None`), it means there's really nothing (non-inclusion). Otherwise it gives you the node you previosly stored. This easy non-inclusion proving is one of the main reasons we use sparse merkle trees. 

This requires lots of hashes initially stored, but luckily as they are mostly hahses of 

* `None`
* `hash(None)`
* `hash(hash(None))`
* `hash(hash(hash(None)))` 
* ... (_# of tree depth_)

This observation allowed me to optimize `monotree` like this: 

1. Initially cache those hash values above.
2. Keep compressed every path as much as possible when inserting so that it can reduce the number of db works in both reads and wrties.

I'm sure you've got already your own answer, but I'm writing for someone with the same question.
